// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXYedN9RWDBdnIQdA00EeDggAgfnonrAI',
    appId: '1:161222852953:android:59c904d713b999ba890c48',
    messagingSenderId: '161222852953',
    projectId: 'vibenou-5d701',
    storageBucket: 'vibenou-5d701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyUfdAfuwF4UtfFCaHVuV9rcL4iL4zFDs',
    appId: '1:161222852953:ios:0b12d1ef1932b1f5890c48',
    messagingSenderId: '161222852953',
    projectId: 'vibenou-5d701',
    storageBucket: 'vibenou-5d701.firebasestorage.app',
    iosBundleId: 'com.vibenou.vibenou',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm4M3jeSw4E54FGQoAaI6q5BvQtMf54ls',
    authDomain: 'vibenou-5d701.firebaseapp.com',
    projectId: 'vibenou-5d701',
    storageBucket: 'vibenou-5d701.firebasestorage.app',
    messagingSenderId: '161222852953',
    appId: '1:161222852953:web:d8c69996270b0a63890c48',
  );
}
